site_name: Documentation
site_url: https://docs.dyalog.com/21.0/
repo_url: https://github.com/dyalog/documentation
copyright: Made with <a href="https://squidfunk.github.io/mkdocs-material/" target="_blank" rel="noopener"><strong>Material for MkDocs</strong></a><br/>Copyright &copy; 1982-$CURRENT_YEAR <strong><a href="https://dyalog.com" target="_blank" rel="noopener">Dyalog Limited</a></strong> (<a href="#" class="copy" onclick="navigator.clipboard.writeText(innerText);return false" title="Click to copy!">$BUILD_DATE $GIT_INFO</a>).<br/>Except where otherwise noted, content on this site is licensed under a <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener"><strong>Creative Commons Attribution 4.0 International</strong></a> licence.


theme:
  favicon: 'documentation-assets/images/favicon-32.png'
  logo: documentation-assets/images/dyalog-logo_white.svg
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.path
    - navigation.indexes
    - navigation.sections
    - navigation.footer
  name: material
  font:
      text: Be Vietnam Pro

extra_css:
  - documentation-assets/css/main.css
  - documentation-assets/css/extra.css
  - documentation-assets/css/admonition-ucmdhelp.css
  - documentation-assets/css/windows-ui-guide.css
plugins:
  - privacy
  - search
  - macros
  - monorepo
  - caption:
      table:
        enable: true
        start_index: 1
        increment_index: 1
        position: top
        reference_text: 'Table {index}'
        caption_prefix: 'Table {index}:'
  - minify:
      minify_html: true

extra:
  version_maj: 21
  version_min: 0
  version_majmin: "21.0"
  version_condensed: 210
  conga_version: 3.6
  conga_version_condensed: 36
  version:
    provider: mike
  generator: false
  key: '[<svg xmlns="http://www.w3.org/2000/svg" fill="white" height="32" viewBox="-4 0 16 24" width="32"><path d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8Zm8-6.5a6.5 6.5 0 1 0 0 13 6.5 6.5 0 0 0 0-13ZM6.5 7.75A.75.75 0 0 1 7.25 7h1a.75.75 0 0 1 .75.75v2.75h.25a.75.75 0 0 1 0 1.5h-2a.75.75 0 0 1 0-1.5h.25v-2h-.25a.75.75 0 0 1-.75-.75ZM8 6a1 1 0 1 1 0-2 1 1 0 0 1 0 2Z"></path></svg>](/21.0/language-reference-guide/key-to-notation)'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: false
      pygments_lang_class: true
  - attr_list
  - abbr
  - footnotes
  - md_in_html
  - markdown_tables_extended
  - toc:
      title: On this page

nav:
  - 'Release Notes':
        - 'v21.0 Release Notes': "!include ./release-notes/mkdocs.yml"
        - 'Earlier Release Notes': "!include ./earlier-release-notes/mkdocs.yml"
  - 'Core Reference':
        - 'Dyalog APL Language': "!include ./language-reference-guide/mkdocs.yml"
        - 'Programming': "!include ./programming-reference-guide/mkdocs.yml"
  - 'Code Tooling':
        - '.NET Interface': "!include ./dotnet-interface-guide/mkdocs.yml"
        - 'Compiler': "!include ./compiler-user-guide/mkdocs.yml"
        - 'Shared Code Files': "!include ./shared-code-files-user-guide/mkdocs.yml"
  - 'Dyalog for Microsoft Windows':
        - 'Installation/Configuration': "!include ./windows-installation-and-configuration-guide/mkdocs.yml"
        - 'User Interface': "!include ./windows-ui-guide/mkdocs.yml"
        - 'Object Reference': "!include ./object-reference/mkdocs.yml"
        - 'Interfaces': "!include ./interface-guide/mkdocs.yml"
        - '.NET Framework Interface': "!include ./dotnet-framework-interface-guide/mkdocs.yml"
  - 'Dyalog for Unix': 
        - 'Installation/Configuration': "!include ./unix-installation-and-configuration-guide/mkdocs.yml"       
        - 'User Interface': "!include ./unix-user-guide/mkdocs.yml"
  - 'About':
        - 'Conventions': conventions.md
        - 'Third-party Licences': licences-overview.md
        - 'Trademarks': trademarks.md