site_name: Windows Installation and Configuration Guide
theme:
  favicon: documentation-assets/images/favicon-32.png
  logo: documentation-assets/images/dyalog-logo_white.svg
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.path
    - navigation.indexes
    - navigation.footer
  name: material
  font:
    text: Be Vietnam Pro
extra_css:
  - documentation-assets/css/main.css
  - documentation-assets/css/extra.css
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
plugins:
  - privacy
  - search
  - macros
  - site-urls
  - caption:
      table:
        enable: true
        start_index: 1
        increment_index: 1
        position: top
        reference_text: 'Table {index}'
        caption_prefix: 'Table {index}:' 
extra:
  version_maj: 20
  version_majmin: 20.0
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      use_pygments: false
  - attr_list
  - abbr
  - footnotes
  - md_in_html
  - markdown_tables_extended
  - toc:
      title: On this page
nav:
  - index.md
  - Documentation: documentation.md
  - Files and Directories: files-and-directories.md
  - File Extensions: file-associations.md
  - APL Fonts: apl-fonts.md
  - Interoperability and Compatibility: interoperability.md
  - The APL Command Line: apl-command-line.md
  - APL Exit Codes: apl-exit-codes.md
  - Dyalog Serial Number: dyalog-serial-number.md
  - Registry SubFolders: registry-subfolders.md
  - Configuration Files: configuration-files.md
  - Window Captions: window-captions.md
  - Workspace Management: workspace-management.md
  - Interface with Windows: interface-with-windows.md
  - Auxiliary Processors: auxiliary-processors.md
  - Access Control for External Variables: access-control-for-external-variables.md
  - Shell Scripts: shell-scripts.md
  - Creating Executables: creating-executables.md
  - Run-Time Applications and Components: runtime-applications-and-components.md
  - Run-Time Applications Additional Considerations: runtime-applications-additional.md
  - COM Objects and the Dyalog APL DLL: com-objects-and-the-dyalog-dll.md
  - APL Application as a Service: apl-application-as-a-service.md
  - APLService Logging Events: aplservice-logging-events.md
  - Configuring the IDE:
      - Configuration Dialog:
          - General Tab: configuring-the-ide/configuration-dialog/configuration-dialog-general-tab.md
          - Unicode Input Tab: 
              configuring-the-ide/configuration-dialog/configuration-dialog-unicode-input-tab-unicode-edition-only.md
          - Input Tab (Classic Edition): 
              configuring-the-ide/configuration-dialog/configuration-dialog-input-tab-classic-edition-only.md
          - Output Tab (Classic Edition): 
              configuring-the-ide/configuration-dialog/configuration-dialog-output-tab-classic-edition-only.md
          - Keyboard Shortcuts Tab: 
              configuring-the-ide/configuration-dialog/configuration-dialog-keyboard-shortcuts-tab.md
          - Workspace Tab: configuring-the-ide/configuration-dialog/configuration-dialog-workspace-tab.md
          - Help/DMX Tab: configuring-the-ide/configuration-dialog/configuration-dialog-help-dmx-tab.md
          - Windows Tab: configuring-the-ide/configuration-dialog/configuration-dialog-windows-tab.md
          - Session Tab: configuring-the-ide/configuration-dialog/configuration-dialog-session-tab.md
          - Trace/Edit Tab: configuring-the-ide/configuration-dialog/configuration-dialog-trace-edit-tab.md
          - Auto Complete Tab: 
              configuring-the-ide/configuration-dialog/configuration-dialog-auto-complete-tab.md
          - SALT Tab: configuring-the-ide/configuration-dialog/configuration-dialog-salt-tab.md
          - User Commands Tab: 
              configuring-the-ide/configuration-dialog/configuration-dialog-user-commands-tab.md
          - Object Syntax Tab: 
              configuring-the-ide/configuration-dialog/configuration-dialog-object-syntax-tab.md
          - Saved ResponsesTab: 
              configuring-the-ide/configuration-dialog/configuration-dialog-saved-responsestab.md
      - Colour Selection Dialog: configuring-the-ide/colour-selection-dialog.md
      - Print Configuration Dialog: configuring-the-ide/print-configuration.md
