site_name: Earlier Release Notes
theme:
  favicon: documentation-assets/images/favicon-32.png
  logo: documentation-assets/images/dyalog-logo_white.svg
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.path
    - navigation.indexes
  name: material
  font:
    text: Be Vietnam Pro
extra_css:
  - documentation-assets/css/main.css
  - documentation-assets/css/extra.css
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
plugins:
  - privacy
  - search
  - macros
  - site-urls
  - caption:
      table:
        enable: true
        start_index: 1
        increment_index: 1
        position: bottom
extra:
  version_maj: 20
  version_majmin: 20.0
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - abbr
  - footnotes
  - md_in_html
  - markdown_tables_extended
  - toc:
      title: On this page
nav:
  - Dyalog v19.0 Release Notes:
    - Introduction:
        - Key Features: release-notes-v19-0/introduction/key-features.md
        - Extension to Native File Functions: release-notes-v19-0/introduction/extension-to-native-file-functions.md
        - Lexical Scope in Scripts: release-notes-v19-0/introduction/lexical-scope-in-scripts.md
        - Session Gutter: release-notes-v19-0/introduction/session-gutter.md
        - Source as Typed: release-notes-v19-0/introduction/source-as-typed.md
        - Bug Fixes: release-notes-v19-0/introduction/bug-fixes.md
        - Announcements: release-notes-v19-0/introduction/announcements.md
        - System Requirements: release-notes-v19-0/introduction/requirements.md
        - Interoperability: release-notes-v19-0/introduction/interoperability.md
    - Configuration Parameters:
        - New or Changed Configuration Parameters: release-notes-v19-0/configuration-parameters/changes-to-configuration-parameters.md
        - DYALOG_GUTTER_ENABLE: release-notes-v19-0/configuration-parameters/dyalog-gutter-enable.md
        - DYALOG_DISCARD_FN_SOURCE: release-notes-v19-0/configuration-parameters/dyalog-discard-fn-source.md
        - DYALOG_INITSESSION: release-notes-v19-0/configuration-parameters/dyalog-initsession.md
        - DyalogLink: release-notes-v19-0/configuration-parameters/dyaloglink.md
        - DyalogStartup_X: release-notes-v19-0/configuration-parameters/dyalogstartup-x.md
        - DyalogStartupSE: release-notes-v19-0/configuration-parameters/dyalogstartupse.md
        - Log_File: release-notes-v19-0/configuration-parameters/log-file.md
    - Language Reference Changes:
        - Language Changes: release-notes-v19-0/language-reference-changes/language-enhancements.md
        - File Hold: release-notes-v19-0/language-reference-changes/fhold.md
        - Fix Script: release-notes-v19-0/language-reference-changes/fix.md
        - Allocate Token Range: release-notes-v19-0/language-reference-changes/talloc.md
        - Memory Manager Statistics: release-notes-v19-0/language-reference-changes/memory-manager-statistics.md
        - Enable Compression of Large Components: release-notes-v19-0/language-reference-changes/enable-compression-of-large-components.md
        - Discard Source Information: release-notes-v19-0/language-reference-changes/discard-source-information.md
        - Discard Source Code: release-notes-v19-0/language-reference-changes/discard-source-code.md
        - Hash Table Size: release-notes-v19-0/language-reference-changes/hash-table-size.md
        - Lookup Table Size: release-notes-v19-0/language-reference-changes/lookup-table-size.md
    - Object Reference Changes:
        - AllowContextMenu: release-notes-v19-0/object-reference-changes/allowcontextmenu.md
        - ExecuteJavaScript: release-notes-v19-0/object-reference-changes/executejavascript.md
        - GetZoomLevel: release-notes-v19-0/object-reference-changes/getzoomlevel.md
        - IsLoading: release-notes-v19-0/object-reference-changes/isloading.md
        - LoadEnd: release-notes-v19-0/object-reference-changes/loadend.md
        - SetZoomLevel: release-notes-v19-0/object-reference-changes/setzoomlevel.md
