site_name: Dyalog Configuration Guide
theme:
  favicon: documentation-assets/images/favicon-32.png
  logo: documentation-assets/images/dyalog-logo_white.svg
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.path
    - navigation.indexes
    - navigation.footer
  name: material
  font:
    text: Be Vietnam Pro
extra_css:
  - documentation-assets/css/main.css
  - documentation-assets/css/extra.css
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
plugins:
  - privacy
  - search
  - macros
  - site-urls
  - caption:
      table:
        enable: true
        start_index: 1
        increment_index: 1
        position: top
        reference_text: 'Table {index}'
        caption_prefix: 'Table {index}:'
extra:
  version_maj: 21
  version_majmin: "21.0"
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      use_pygments: false
  - attr_list
  - abbr
  - footnotes
  - md_in_html
  - markdown_tables_extended
  - toc:
      title: On this page
nav:
  - index.md
  - Introduction: introduction.md
  - How to Set Configuration Parameters:
      - Overview: how-to-set/overview.md
      - Order of Precedence: how-to-set/order-of-precedence.md
      - Command Line: how-to-set/command-line.md
      - Application Configuration Files: how-to-set/application-configuration-files.md
      - Environment Variables: how-to-set/environment-variables.md
      - User Configuration Files: how-to-set/user-configuration-files.md
      - Windows Registry: how-to-set/registry.md
      - Built-in Defaults: how-to-set/built-in-defaults.md
      - Configuration File Structure: how-to-set/configuration-file-structure.md
