site_name: Compiler User Guide
theme:
  favicon: documentation-assets/images/favicon-32.png
  logo: documentation-assets/images/dyalog-logo_white.svg
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.path
    - navigation.indexes
  name: material
  font:
    text: Be Vietnam Pro
extra_css:
  - documentation-assets/css/main.css
  - documentation-assets/css/extra.css
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
plugins:
  - privacy
  - search
  - macros
  - site-urls
  - caption:
      table:
        enable: true
        start_index: 1
        increment_index: 1
        position: bottom
        reference_text: 'Table {index}'
        caption_prefix: 'Table {index}:' 
extra:
  version_maj: 20
  version_majmin: 20.0
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      use_pygments: false
  - attr_list
  - abbr
  - footnotes
  - md_in_html
  - markdown_tables_extended
  - toc:
      title: On this page
nav:
  - index.md
  - Introduction:
      - introduction/index.md
      - Optimisations: introduction/optimisations.md
      - Changes to Behaviour of Functions when Compiled: introduction/changes-to-behaviour.md
      - Upgrading from Previous Versions of Dyalog: introduction/upgrading-from-previous-dyalog-versions.md
  - Basic Usage: basic-usage.md
  - Compiling with Global Names: compiling-with-global-names.md
  - Compiling Operators: compiling-operators.md
  - Restrictions: restrictions.md
  - Compiler Control I-beam: compiler-control-ibeam.md

